aliases: []
creation_timestamp: 1711825470316
current_stage: Production
description: ''
last_updated_timestamp: 1711960500317
name: Sentiment_analysis_review_prediction_experiment
run_id: d2a30d2712a04d55ac4739b5ddc35146
run_link: ''
source: mlflow-artifacts:/859695253251303284/d2a30d2712a04d55ac4739b5ddc35146/artifacts/best_estimator
status: READY
status_message: null
storage_location: mlflow-artifacts:/859695253251303284/d2a30d2712a04d55ac4739b5ddc35146/artifacts/best_estimator
user_id: null
version: 5
