aliases: []
creation_timestamp: 1711827885862
current_stage: None
description: ''
last_updated_timestamp: 1711827885862
name: Sentiment_analysis_review_prediction_experiment
run_id: 2c176bb6a5174cd7838dda2836cce1fc
run_link: ''
source: mlflow-artifacts:/859695253251303284/2c176bb6a5174cd7838dda2836cce1fc/artifacts/best_estimator
status: READY
status_message: null
storage_location: mlflow-artifacts:/859695253251303284/2c176bb6a5174cd7838dda2836cce1fc/artifacts/best_estimator
user_id: null
version: 6
