aliases: []
creation_timestamp: 1711823125255
current_stage: Archived
description: ''
last_updated_timestamp: 1711960500317
name: Sentiment_analysis_review_prediction_experiment
run_id: 1108bcdcc6ca46b5a00d06448999e16f
run_link: ''
source: mlflow-artifacts:/859695253251303284/1108bcdcc6ca46b5a00d06448999e16f/artifacts/best_estimator
status: READY
status_message: null
storage_location: mlflow-artifacts:/859695253251303284/1108bcdcc6ca46b5a00d06448999e16f/artifacts/best_estimator
user_id: null
version: 1
